name: GitHub Enterprise Sync

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Waka Readme"]
    types:
      - completed
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "Edward-Ji/Edward-Ji"
          source_branch: "main"
          destination_repo: "https://ZIJI4098:${{ secrets.GH_ENTERPRISE_TOKEN }}@github.sydney.edu.au/ZIJI4098/ZIJI4098.git"
          destination_branch: "main"
